- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Atlas
  - Bagel
  - Box
  - Cluster
  - Core
  - Fland
<<<<<<< HEAD
  # - Kettle
=======
>>>>>>> upstream/master
  - Marathon
  - Meta
  - Gemini
  - Omega
  - Origin
  - Saltern
  - Packed
  - Reach
