<<<<<<< HEAD:Resources/Prototypes/Roles/Jobs/Security/detective.yml
- type: job
  id: Detective
  name: job-name-detective
  description: job-description-detective
  playTimeTracker: JobDetective
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 54000 # 15 hours
  startingGear: DetectiveGear
  icon: "JobIconDetective"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  - Brig
  - Maintenance
  - Service
  - Detective
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: DetectiveGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDetective
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsJackSec # Corvax-Resprite
    eyes: ClothingEyesGlassesSunglasses
    head: ClothingHeadHatFedoraBrown
    outerClothing: ClothingOuterVestDetective
    id: DetectivePDA
    ears: ClothingHeadsetSecurity
    pocket1: ForensicPad
    pocket2: ForensicScanner
    belt: ClothingBeltHolsterFilled
    gloves: ClothingHandsGlovesForensic
    underwearb: ClothingUnderwearBottomBoxersWhite # Sirena-Underwear
    socks: ClothingUnderwearSocksNormal
    neck: ADTClothingNeckSecBadge
  underweart: ClothingUnderwearTopBraSportsAlternative # Sirena-Underwear
  underwearb: ClothingUnderwearBottomPantiesWhite # Sirena-Underwear
  innerClothingSkirt: ClothingUniformJumpskirtDetective
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
=======
- type: job
  id: Detective
  name: job-name-detective
  description: job-description-detective
  playTimeTracker: JobDetective
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 36000 # 10 hours
  - !type:DepartmentTimeRequirement
    department: Civilian
    time: 18000 # 5 hours
  startingGear: DetectiveGear
  icon: "JobIconDetective"
  supervisors: job-supervisors-hop
  canBeAntag: true
  access:
  - Brig
  - Maintenance
  - Service
  - Detective
  extendedAccess:
  - Security

- type: startingGear
  id: DetectiveGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitDetective
    outerClothing: ClothingOuterVestDetective
    back: ClothingBackpackFilledDetective
    shoes: ClothingShoesBootsJack
    eyes: ClothingEyesGlassesSunglasses
    head: ClothingHeadHatFedoraBrown
    id: DetectivePDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltHolsterFilled
  innerClothingSkirt: ClothingUniformJumpskirtDetective
  satchel: ClothingBackpackSatchelFilledDetective
  duffelbag: ClothingBackpackDuffelFilledDetective
>>>>>>> upstream/master:Resources/Prototypes/Roles/Jobs/Civilian/detective.yml
